language: c
notifications:
 irc:
  channels: "anathema.irc.so#anathema"
  use_notice: true
  skip_join: true
compiler:
 - clang
 - gcc
before_install:
 - sudo add-apt-repository ppa:ukplc-team/ppa -y
 - sudo apt-get update -qq
install:
 - sudo apt-get install -y help2man libjansson-dev libev-dev
before_script:
 - mkdir build
 - cd build
script:
 - cmake .. -DCMAKE_INSTALL_PREFIX=/usr
 - make
 - cpack -G DEB
