language: c
notifications:
 irc:
  channels: "irc.janouch.name#dev"
  use_notice: true
  skip_join: true
env:
 global:
  - secure: "Xe3sUsIDBcyA1orysIgtj4Mh5n3gfDlc5ERSzFDptTdP45wvmXiaBGi332XdudXWiVW1tW9MAF+BX27CpIf01L9g8b88+XIkUXQoWOLzT3Yrp9O+aEF4xoCCODQKAtVaYay9+GPQkJ65+pnM+mG6K7pAnyBjckn7DGcKSpt12kM="
addons:
 coverity_scan:
  project:
   name: "pjanouch/json-rpc-shell"
   description: "Shell for JSON-RPC 2.0 HTTP queries"
  notification_email: p.janouch@gmail.com
  build_command_prepend: "cmake .. -DCMAKE_BUILD_TYPE=Release"
  build_command: "make"
  branch_pattern: coverity_scan
compiler:
 - clang
 - gcc
before_install:
 - sudo add-apt-repository ppa:ukplc-team/ppa -y
 - sudo apt-get update -qq
install:
 - sudo apt-get install -y help2man libcurl4-openssl-dev libjansson-dev libev-dev libreadline-dev libncursesw5-dev
before_script:
 - mkdir build
 - cd build
script:
 - cmake .. -DCMAKE_INSTALL_PREFIX=/usr
 - make
 - cpack -G DEB
