language: c
notifications:
 irc:
  channels: "irc.janouch.name#dev"
  use_notice: true
  skip_join: true
  template:
   - "%{repository_name}#%{build_number} on %{branch}: %{message}"
   - "  %{compare_url}"
   - "  %{build_url}"
  on_success: change
  on_failure: always
compiler:
 - clang
 - gcc
before_install:
 - sudo add-apt-repository ppa:ukplc-team/ppa -y
 - sudo apt-get update -qq
install:
 - sudo apt-get install -y help2man libjansson-dev libev-dev
before_script:
 - mkdir build
 - cd build
script:
 - cmake .. -DCMAKE_INSTALL_PREFIX=/usr
 - make
 - cpack -G DEB
