json-rpc-shell
==============
:compact-option:

'json-rpc-shell' is a simple shell for running JSON-RPC 2.0 queries.

This software has been created as a replacement for the following shell, which
is written in Java: http://software.dzhuvinov.com/json-rpc-2.0-shell.html

Features
--------
In addition to most of the features provided by Vladimir Dzhuvinov's shell
you get the following niceties:

 - configurable JSON syntax highlight, which with prettyprinting turned on
   helps you make sense of the results significantly
 - ability to pipe output through a shell command, so that you can view the
   results in your favourite editor or redirect them to a file
 - ability to edit the input line in your favourite editor as well with Alt+E
 - WebSocket (RFC 6455) can also be used as a transport rather than HTTP
 - support for method name tab completion using OpenRPC discovery

Documentation
-------------
See the link:json-rpc-shell.adoc[man page] for information about usage.
The rest of this README will concern itself with externalities.

Packages
--------
Regular releases are sporadic.  git master should be stable enough.  You can get
a package with the latest development version from Archlinux's AUR.

Building
--------
Build dependencies: CMake, pkg-config, asciidoctor,
                    liberty (included), http-parser (included) +
Runtime dependencies: libev, Jansson, cURL, openssl,
                      readline or libedit >= 2013-07-12,

Avoid libedit if you can, in general it works but at the moment history is
acting up and I have no clue about fixing it.  Multiline editing is also
misbehaving there.

 $ git clone --recursive https://git.janouch.name/p/json-rpc-shell.git
 $ mkdir json-rpc-shell/build
 $ cd json-rpc-shell/build
 $ cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug
 $ make

To install the application, you can do either the usual:

 # make install

Or you can try telling CMake to make a package for you.  For Debian it is:

 $ cpack -G DEB
 # dpkg -i json-rpc-shell-*.deb

Note that for versions of CMake before 2.8.9, you need to prefix `cpack` with
`fakeroot` or file ownership will end up wrong.

Test server
-----------
If you install development packages for libmagic, an included test server will
be built but not installed which provides a trivial JSON-RPC 2.0 service with
FastCGI, SCGI, and WebSocket interfaces.  It responds to `ping` and `date`
methods and it can serve static files.

Contributing and Support
------------------------
Use https://git.janouch.name/p/json-rpc-shell to report bugs, request features,
or submit pull requests.  `git send-email` is tolerated.  If you want to discuss
the project, feel free to join me at ircs://irc.janouch.name, channel #dev.

Bitcoin donations are accepted at: 12r5uEWEgcHC46xd64tt3hHt9EUvYYDHe9

License
-------
This software is released under the terms of the 0BSD license, the text of which
is included within the package along with the list of authors.
